# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangen', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('handler', models.CharField(default='', max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(verbose_name='\u7b2c\u51e0\u6b21\u56de\u5f52')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DateField(verbose_name='\u5468\u7248\u672c')),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regress.Count'),
        ),
        migrations.AddField(
            model_name='context',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regress.Version'),
        ),
    ]
