# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='count',
            field=models.CharField(choices=[('\u7b2c\u4e00\u6b21', '\u7b2c\u4e00\u6b21\u56de\u5f52'), ('\u7b2c\u4e8c\u6b21', '\u7b2c\u4e8c\u6b21\u56de\u5f52')], default='\u7b2c\u4e00\u6b21', max_length=10, verbose_name='\u7b2c\u51e0\u6b21\u56de\u5f52'),
        ),
    ]
