# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='detail',
            field=models.TextField(blank=True, max_length=200, verbose_name='\u8865\u5145\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='version',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='\u5907\u6ce8'),
        ),
    ]
