# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regress', '0002_auto_20180210_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='detail',
            field=models.TextField(max_length=200, verbose_name='\u8865\u5145\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='context',
            name='handler',
            field=models.CharField(default='', max_length=10, verbose_name='\u786e\u8ba4\u4eba'),
        ),
        migrations.AlterField(
            model_name='context',
            name='rangen',
            field=models.CharField(choices=[('\u7070\u5ea6', '\u7070\u5ea6'), ('\u975e\u7070\u5ea6', '\u975e\u7070\u5ea6'), ('\u5c0f\u7ec4', '\u5c0f\u7ec4')], default='\u7070\u5ea6', max_length=10, verbose_name='\u8303\u56f4'),
        ),
        migrations.AlterField(
            model_name='context',
            name='status',
            field=models.BooleanField(default=False, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='context',
            name='title',
            field=models.TextField(max_length=200, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='count',
            name='count',
            field=models.IntegerField(choices=[(0, '\u7b2c\u4e00\u6b21\u56de\u5f52'), (1, '\u7b2c\u4e8c\u6b21\u56de\u5f52')], default=0, verbose_name='\u7b2c\u51e0\u6b21\u56de\u5f52'),
        ),
    ]
