# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regress', '0003_auto_20180225_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='participant',
            field=models.CharField(default='', max_length=100, verbose_name='\u53c2\u4e0e\u8005'),
        ),
    ]
