# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regress', '0004_context_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='partyusername',
            field=models.CharField(default='', max_length=100, verbose_name='\u53c2\u4e0e\u8005\u8d26\u6237'),
        ),
    ]
