# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='\u53d1\u8d77\u4eba')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('already_votes', models.CharField(default='', max_length=1000)),
                ('choose', models.CharField(choices=[('\u6295\u7968', '\u6295\u7968'), ('\u6295\u7968', '\u95ee\u7b54')], default='\u6295\u7968', max_length=15, verbose_name='\u7c7b\u578b')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
