# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceText', models.CharField(max_length=200, verbose_name='\u95ee\u9898')),
                ('choiceAnswar', models.CharField(default='', max_length=200, verbose_name='\u95ee\u7b54\u7ed3\u679c')),
                ('choiceVote', models.IntegerField(default=0, verbose_name='\u6295\u7968\u7ed3\u679c')),
                ('whoVote', models.CharField(blank=True, default='', max_length=200, verbose_name='\u6295\u7968\u4eba')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='already_votes',
            new_name='alreadyVote',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Question'),
        ),
    ]
