# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20171202_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choose',
        ),
        migrations.AddField(
            model_name='question',
            name='choose_1',
            field=models.BooleanField(default=False, verbose_name='\u6295\u7968'),
        ),
        migrations.AddField(
            model_name='question',
            name='choose_2',
            field=models.BooleanField(default=False, verbose_name='\u95ee\u7b54'),
        ),
    ]
