# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180309_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceAnswar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='\u95ee\u7b54\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceText',
            field=models.TextField(max_length=200, verbose_name='\u95ee\u9898'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceVote',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u6295\u7968\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alreadyVote',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='\u5df2\u53c2\u4e0e\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choose',
            field=models.CharField(choices=[('\u6295\u7968', '\u6295\u7968'), ('\u95ee\u7b54', '\u95ee\u7b54')], default='\u6295\u7968', max_length=15, verbose_name='\u7c7b\u578b'),
        ),
    ]
