# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20171202_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choose_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choose_2',
        ),
        migrations.AddField(
            model_name='question',
            name='choose',
            field=models.NullBooleanField(default=False, verbose_name='\u7c7b\u578b'),
        ),
    ]
