# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20180309_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['pk']},
        ),
    ]
