# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20171202_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='answerer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='choose',
            field=models.NullBooleanField(choices=[('choose_vote', '\u6295\u7968'), ('choose_qa', '\u95ee\u7b54')], verbose_name='\u7c7b\u578b'),
        ),
    ]
