# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20180309_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceAnswer',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='\u95ee\u7b54\u7ed3\u679c'),
        ),
    ]
