# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20171202_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='already_votes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='choice',
            name='who_votes',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
