# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20171206_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_answer',
            field=models.CharField(default='', max_length=400),
        ),
    ]
